### ISSUE TITLE
When submitting a review anonymously, the grade entered in the review was not displayed.

### ISSUE THREAD

**Issue by blazerzero** [jonathan-almeida1993/CourseRater#11]
BUGS CAN BE SEEN ON: course_page.html
FILES CONTAINING BUG: review.js

**Comment by minic-osu** [comment]
Along with this, when a user does not submit their grade in their review, it should not appear in the review at all. Just the fields the user filled out.

**Comment by jonathan-almeida1993** [comment]
I could not recreate this issue. But there seems to be an issue with Anonymous reviews not being anonymous.

**Comment by blazerzero** [comment]
I cannot recreate this issue either. But I can remove the "Grade Received" part if the user does not leave a review

**Comment by jonathan-almeida1993** [comment]
> Along with this, when a user does not submit their grade in their review, it should not appear in the review at all. Just the fields the user filled out.
