### ISSUE TITLE
Multiple reviews are allowed for one course. 

### ISSUE THREAD

**Issue by minic-osu** [jonathan-almeida1993/CourseRater#17]
The user should not be allowed to submit more than one review per course. Right now, if they navigate away from the page and come back, the system allows them to submit another review for the same course. 

Solution:
-For course pages with more than one course ID. Make the pages submit review modal have a note at the top of the modal that says, 'Note: if you have already submitted a review for this, course your review will not be submitted. " if the user goes ahead and still fills out a review, there would be a notification that appears that says their review did not get submitted because they have already reviewed the course. 
-For course pages with only one course ID, the submit review button would appear disabled already and the text would say 'review submitted'.

**Comment by blazerzero** [comment]
This bug has been patched.
