### ISSUE TITLE
User is displayed different rating in 'View Modal' than 'Your Recent Reviews' table. 

### ISSUE THREAD

**Issue by SheekhaJ** [jonathan-almeida1993/CourseRater#22]
Steps to reproduce: 
1) Submit a review by selecting CS 160, Fall 2018, Shannon, no grade, rating 3 and no review text. 
2) Verify that review is submitted and displayed on the Reviews page. 
3) Click on Home button. 
4) In 'Your recent reviews' section, the rating for CS 160, Fall 2018, Shannon is displayed correctly. 
5) Click on corresponding View link
6) Note that rating in 'Your review' modal is different than that displayed in the table.

**Comment by minic-osu** [comment]
My review matches, I'm not seeing this error on the version deployed on digital ocean.

**Comment by blazerzero** [comment]
bug is fixed :)
