### ISSUE TITLE
Search button on Course Page sometimes disabled when it shouldn't be

### ISSUE THREAD

**Issue by blazerzero** [jonathan-almeida1993/CourseRater#6]
On the course page, the Search button is disabled by default. However, if any values are changed from the saved search query, the button should be re-enabled.

However, if I reset the term and instructor fields and then revert just one of them back to the saved value, the search button becomes disabled again. It should only disable if ALL fields are reverted or kept as the saved value.

BUG CAN BE SEEN ON: course_page.html
FILES CONTAINING BUG: review.js

**Comment by minic-osu** [comment]
Along with this bug, there needs to be feedback provided to the user, that when the search button is pressed, there need to be more visual feedback. 
Search button is also clickable, even when in a disabled state.

**Comment by blazerzero** [comment]
The search button is no longer clickable when it's disabled.

**Comment by blazerzero** [comment]
This bug has been patched. I have performed unit tests.
